1.Write a function so that the columns of the output matrix are powers of the input vector [Alexandre-
Theophile Vandermonde matrix].

The i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [1]:
import numpy as np

def ATV_matrix(lst,n=None):
  mat = []
  if n == None:
    n = len(lst)
  else:
    n=n
  for i in range(n):
    for j in lst:
      mat = np.append(mat,(j**(n-1-i)))
  return mat.reshape((n,len(lst))).transpose()

x = [1,2,3,4]
ATV_matrix(x)



array([[ 1.,  1.,  1.,  1.],
       [ 8.,  4.,  2.,  1.],
       [27.,  9.,  3.,  1.],
       [64., 16.,  4.,  1.]])

In [2]:
# Another method

x= np.array([1,2,3,4])
N=4
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

2. Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
(n-k+1 elements (n - values, k - window size))

In [3]:
import numpy as np

def moving_avg(lst,win):
  mw = []
  for i in range(len(lst)): 
    if len(lst[i:i+win]) == win:
      mw = np.append(mw,np.sum(lst[i:i+win])/win)
  return mw

lst = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
window = 3

moving_avg(lst,window)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])